"""Add Document model

Revision ID: 7ca7ddb92db4
Revises: 9a4eb06c9359
Create Date: 2026-01-14 16:19:32.912817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca7ddb92db4'
down_revision = '9a4eb06c9359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('blob_url', sa.String(length=512), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=True),
    sa.Column('target_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
